name = "Ruins-of-the-Ancients-Packwiz-SOLO"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "600fabca936d93698371ecd4d7ea0f3c620a1a0feaf42204c1dcd0e03dca1985"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
