name = "Ruins-of-the-Ancients-Packwiz-SOLO"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e03d3d5c6b7e140383379fd2bfad5a0dc55e2f6995388b53e197502ba002d89"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
