name = "Ruins-of-the-Ancients-Packwiz-SOLO"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49133d9a807867859c63aaae9224c0273fe3a8eda4ddc0caa9c37c0b788815e0"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
