name = "Ruins-of-the-Ancients-Packwiz-SOLO"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "799b531f63edd8c9b508dbb325121fee86d78ce5bb9da9db46d2243588e45560"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
