name = "[ANGRY PIXEL] The Betweenlands"
filename = "TheBetweenlands-3.7.2-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3148/242/TheBetweenlands-3.7.2-universal.jar"
hash-format = "murmur2"
hash = "140648905"

[update]
[update.curseforge]
file-id = 3148242
project-id = 243363
release-channel = "beta"
