name = "[ANGRY PIXEL] The Betweenlands"
filename = "TheBetweenlands-3.7.1-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3099/119/TheBetweenlands-3.7.1-universal.jar"
hash-format = "murmur2"
hash = "3538451540"

[update]
[update.curseforge]
file-id = 3099119
project-id = 243363
release-channel = "beta"
