name = "[ANGRY PIXEL] The Betweenlands"
filename = "TheBetweenlands-3.8.1-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/284/TheBetweenlands-3.8.1-universal.jar"
hash-format = "murmur2"
hash = "897400915"

[update]
[update.curseforge]
file-id = 3540284
project-id = 243363
release-channel = "beta"
