name = "Atum 2: Return to the Sands"
filename = "Atum-1.12.2-2.0.19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3062/133/Atum-1.12.2-2.0.19.jar"
hash-format = "murmur2"
hash = "3686715355"

[update]
[update.curseforge]
file-id = 3062133
project-id = 59621
release-channel = "beta"
