name = "Chunk-Pregenerator"
filename = "Chunk Pregenerator-V1.12-2.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3158/203/Chunk Pregenerator-V1.12-2.4.1.jar"
hash-format = "murmur2"
hash = "1594581737"

[update]
[update.curseforge]
file-id = 3158203
project-id = 267193
release-channel = "beta"
