name = "Chunk-Pregenerator"
filename = "Chunk Pregenerator V1.12-2.4E.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3050/664/Chunk Pregenerator V1.12-2.4E.jar"
hash-format = "murmur2"
hash = "3789332953"

[update]
[update.curseforge]
file-id = 3050664
project-id = 267193
release-channel = "beta"
