name = "Commons0815"
filename = "Commons0815-1.12.2-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/796/Commons0815-1.12.2-1.4.0.jar"
hash-format = "murmur2"
hash = "1923633707"

[update]
[update.curseforge]
file-id = 3248796
project-id = 346326
release-channel = "beta"
