name = "Commons0815"
filename = "Commons0815-1.12.2-1.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3000/327/Commons0815-1.12.2-1.3.8.jar"
hash-format = "murmur2"
hash = "304307324"

[update]
[update.curseforge]
file-id = 3000327
project-id = 346326
release-channel = "beta"
