name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.604.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3130/719/CraftTweaker2-1.12-4.1.20.604.jar"
hash-format = "murmur2"
hash = "1154547795"

[update]
[update.curseforge]
file-id = 3130719
project-id = 239197
release-channel = "beta"
