name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.605.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3132/901/CraftTweaker2-1.12-4.1.20.605.jar"
hash-format = "murmur2"
hash = "2319939299"

[update]
[update.curseforge]
file-id = 3132901
project-id = 239197
release-channel = "beta"
