name = "CreativeCore"
filename = "CreativeCore_v1.10.62_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/979/CreativeCore_v1.10.62_mc1.12.2.jar"
hash-format = "murmur2"
hash = "2040100053"

[update]
[update.curseforge]
file-id = 3419979
project-id = 257814
release-channel = "beta"
