name = "Dirt2Path [FORGE]"
filename = "dirt2path-1.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2606/175/dirt2path-1.8.0.jar"
hash-format = "murmur2"
hash = "1031004075"

[update]
[update.curseforge]
file-id = 2606175
project-id = 264684
release-channel = "beta"
