name = "LibVulpes"
filename = "LibVulpes-1.12.2-0.4.2-85-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3499/791/LibVulpes-1.12.2-0.4.2-85-universal.jar"
hash-format = "murmur2"
hash = "2755347300"

[update]
[update.curseforge]
file-id = 3499791
project-id = 236541
release-channel = "beta"
