name = "LittleTiles"
filename = "LittleTiles_v1.5.20_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/249/LittleTiles_v1.5.20_mc1.12.2.jar"
hash-format = "murmur2"
hash = "2752980871"

[update]
[update.curseforge]
file-id = 3432249
project-id = 257818
release-channel = "beta"
