name = "Moving Elevators"
filename = "movingelevators-1.2.31a-mc1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3159/319/movingelevators-1.2.31a-mc1.12.jar"
hash-format = "murmur2"
hash = "2460022457"

[update]
[update.curseforge]
file-id = 3159319
project-id = 373051
release-channel = "beta"
