name = "MysticalLib"
filename = "mysticallib-1.12.2-1.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/257/mysticallib-1.12.2-1.10.0.jar"
hash-format = "murmur2"
hash = "2360260487"

[update]
[update.curseforge]
file-id = 3243257
project-id = 277064
release-channel = "beta"
