name = "Simple Dimensions"
filename = "SimpleDimensions-MC1.12-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2445/577/SimpleDimensions-MC1.12-1.3.1.jar"
hash-format = "murmur2"
hash = "2964372857"

[update]
[update.curseforge]
file-id = 2445577
project-id = 235444
release-channel = "beta"
