name = "Super Factory Manager ( SFM )"
filename = "SuperFactoryManager-1.12.2-2.0.24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3050/275/SuperFactoryManager-1.12.2-2.0.24.jar"
hash-format = "murmur2"
hash = "2312871599"

[update]
[update.curseforge]
file-id = 3050275
project-id = 306935
release-channel = "beta"
