name = "Tesseract"
filename = "tesseract-1.0.15-mc1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3108/719/tesseract-1.0.15-mc1.12.jar"
hash-format = "murmur2"
hash = "1653832321"

[update]
[update.curseforge]
file-id = 3108719
project-id = 379232
release-channel = "beta"
