name = "Tesseract"
filename = "tesseract-1.0.17-mc1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3146/184/tesseract-1.0.17-mc1.12.jar"
hash-format = "murmur2"
hash = "863893719"

[update]
[update.curseforge]
file-id = 3146184
project-id = 379232
release-channel = "beta"
