name = "Tesseract"
filename = "tesseract-1.0.23-mc1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/193/tesseract-1.0.23-mc1.12.jar"
hash-format = "murmur2"
hash = "2972814032"

[update]
[update.curseforge]
file-id = 3414193
project-id = 379232
release-channel = "beta"
