name = "UniDict"
filename = "UniDict-1.12.2-3.0.1.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3130/983/UniDict-1.12.2-3.0.1.jar"
hash-format = "murmur2"
hash = "1316734205"

[update]
[update.curseforge]
file-id = 3130983
project-id = 244258
release-channel = "beta"
